name: Build and Deploy Full Application

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-southeast1
  BACKEND_SERVICE_NAME: realtime-sentiment-app
  DASHBOARD_SERVICE_NAME: realtime-dashboard
  REPO_NAME: realtime-sentiment-repo

jobs:
  deploy-backend:
    name: 1. Deploy Backend API
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.BACKEND_SERVICE_NAME }}:${{ github.sha }} -f Dockerfile .
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.BACKEND_SERVICE_NAME }}:${{ github.sha }}

      # <<< นี่คือส่วนที่แก้ไขให้ฉลาดขึ้น >>>
      - name: Deploy Backend and Get URL with Retry
        id: deploy
        run: |
          gcloud run deploy ${{ env.BACKEND_SERVICE_NAME }} \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.BACKEND_SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"

          echo "Waiting for service to be ready..."
          URL=""
          for i in {1..5}; do
            URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} --platform managed --region ${{ env.GCP_REGION }} --format 'value(status.url)' 2>/dev/null)
            if [ -n "$URL" ]; then
              echo "Successfully fetched URL: $URL"
              break
            fi
            echo "Attempt $i: Service not ready, waiting 15 seconds..."
            sleep 15
          done

          if [ -z "$URL" ]; then
            echo "::error::Could not fetch service URL after multiple attempts."
            exit 1
          fi

          echo "url=$URL" >> $GITHUB_OUTPUT

  deploy-dashboard:
    name: 2. Deploy Frontend Dashboard
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Dashboard Image
        run: |
          docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.DASHBOARD_SERVICE_NAME }}:${{ github.sha }} -f dashboard.Dockerfile .
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.DASHBOARD_SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy Dashboard
        run: |
          BACKEND_WS_URL=$(echo "${{ needs.deploy-backend.outputs.backend_url }}" | sed 's|https|wss|')/ws
          gcloud run deploy ${{ env.DASHBOARD_SERVICE_NAME }} \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.DASHBOARD_SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="BACKEND_WS_URL=$BACKEND_WS_URL"